name: Generate Profile Summary Card

on:
  schedule:
    - cron: "30 18 * * *"  # once daily
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: x0can
          BRANCH_NAME: output
          AUTO_PUSH: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
